name: Spring Boot CI (Gradle Kotlin)

on:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'main'
      - 'feature/**'   # Ejecuta CI en branches que empiecen con "feature/"
      - 'bugfix/**'    # Captura branches de fixes
  pull_request:
    branches:
      - 'develop'
      - 'staging'
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew clean build

      - name: Upload Test Reports (opcional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/

  # Deploy sólo aplica para staging/main (opcional)
  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "Deploying to Staging..."
            # ./gradlew deployToStaging
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo " Deploying to Production..."
            # ./gradlew deployToProd
          fi